// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Artifact represents a single required file for an instance.
 */
export interface Artifact {
    "role": ArtifactRole;
    "url": string;
    "path": string;
    "size": number;
    "sha1": string;
    "rules"?: Rule[] | null;
    "required": boolean;
}

/**
 * ArtifactRole identifies the type of artifact.
 */
export enum ArtifactRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleClient = "client",
    RoleLibrary = "library",
    RoleNative = "native",
    RoleAsset = "asset",
    RoleLegacyResource = "legacy_resource",
};

/**
 * FeatureRule matches against feature flags from version metadata.
 */
export interface FeatureRule {
    "is_demo_user"?: boolean | null;
    "has_custom_resolution"?: boolean | null;
    "has_quick_plays_support"?: boolean | null;
    "is_quick_play_singleplayer"?: boolean | null;
    "is_quick_play_multiplayer"?: boolean | null;
    "is_quick_play_realms"?: boolean | null;
}

/**
 * OSRule matches against operating system properties.
 */
export interface OSRule {
    "name"?: string;
    "arch"?: string;
    "version"?: string;
}

/**
 * Rule defines an allow/disallow condition for libraries, natives, or arguments.
 */
export interface Rule {
    "action": string;
    "os"?: OSRule | null;
    "features"?: FeatureRule | null;
}
