// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * Argument is either a plain string or a conditional object with rules and values.
 */
export type Argument = any;

/**
 * Arguments holds game and JVM arguments.
 */
export interface Arguments {
    "game": Argument[] | null;
    "jvm": Argument[] | null;
}

/**
 * Artifact represents a single required file for an instance.
 */
export interface Artifact {
    "role": ArtifactRole;
    "url": string;
    "path": string;
    "size": number;
    "sha1": string;
    "rules"?: Rule[] | null;
    "required": boolean;
}

/**
 * ArtifactPlan is the complete set of artifacts needed for a version.
 */
export interface ArtifactPlan {
    "versionId": string;
    "artifacts": Artifact[] | null;
}

/**
 * ArtifactRole identifies the type of artifact.
 */
export enum ArtifactRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleClient = "client",
    RoleLibrary = "library",
    RoleNative = "native",
    RoleAsset = "asset",
    RoleLegacyResource = "legacy_resource",
};

/**
 * AssetIndex points to the asset index JSON file.
 */
export interface AssetIndex {
    "id": string;
    "sha1": string;
    "size": number;
    "totalSize": number;
    "url": string;
}

/**
 * DownloadInfo describes a single downloadable artifact.
 */
export interface DownloadInfo {
    "sha1": string;
    "size": number;
    "url": string;
    "path"?: string;
}

/**
 * Downloads holds download info for client, server, and mappings.
 */
export interface Downloads {
    "client"?: DownloadInfo | null;
    "server"?: DownloadInfo | null;
    "client_mappings"?: DownloadInfo | null;
    "server_mappings"?: DownloadInfo | null;
}

/**
 * ExtractRule defines which files to exclude during native extraction.
 */
export interface ExtractRule {
    "exclude": string[] | null;
}

/**
 * FeatureRule matches against feature flags.
 */
export interface FeatureRule {
    "is_demo_user"?: boolean | null;
    "has_custom_resolution"?: boolean | null;
}

/**
 * JavaVersion specifies which Java version is required.
 */
export interface JavaVersion {
    "component": string;
    "majorVersion": number;
}

/**
 * Library is a Minecraft dependency library.
 */
export interface Library {
    "downloads"?: LibraryDownloads | null;
    "name": string;
    "url"?: string;
    "natives"?: { [_ in string]?: string } | null;
    "extract"?: ExtractRule | null;
    "rules"?: Rule[] | null;
    "classifiers"?: { [_ in string]?: DownloadInfo } | null;
}

/**
 * LibraryDownloads holds the main artifact and optional classifiers.
 */
export interface LibraryDownloads {
    "artifact": DownloadInfo;
    "classifiers"?: { [_ in string]?: DownloadInfo } | null;
}

/**
 * LogFileInfo is metadata about the logging config file.
 */
export interface LogFileInfo {
    "id": string;
    "sha1": string;
    "size": number;
    "url": string;
}

/**
 * Logging defines client-side logging configuration.
 */
export interface Logging {
    "client"?: LoggingConfig | null;
}

/**
 * LoggingConfig describes the logging configuration file.
 */
export interface LoggingConfig {
    "argument": string;
    "file": LogFileInfo;
    "type": string;
}

/**
 * OSRule matches against operating system properties.
 */
export interface OSRule {
    "name"?: string;
    "arch"?: string;
    "version"?: string;
}

/**
 * Rule defines an allow/disallow condition for libraries, natives, or arguments.
 */
export interface Rule {
    "action": string;
    "os"?: OSRule | null;
    "features"?: FeatureRule | null;
}

/**
 * VersionDetail is the full metadata for a single Minecraft version.
 */
export interface VersionDetail {
    "arguments"?: Arguments | null;
    "assetIndex": AssetIndex;
    "assets": string;
    "complianceLevel"?: number | null;
    "downloads": Downloads;
    "id": string;
    "jar"?: string;
    "javaVersion": JavaVersion;
    "libraries": Library[] | null;
    "logging"?: Logging | null;
    "mainClass": string;
    "minecraftArguments"?: json$0.RawMessage;
    "minimumLauncherVersion": number;
    "inheritsFrom"?: string;
    "releaseTime": string;
    "time": string;
    "type": string;
}
