// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Options holds launch configuration for a Minecraft instance.
 */
export class Options {
    "PlayerName": string;
    "UUID": string;
    "AccessToken": string;

    /**
     * "offline", "ely.by", "microsoft"
     */
    "UserType": string;
    "VersionID": string;
    "GameDir": string;
    "AssetsDir": string;
    "NativesDir": string;
    "RamMB": number;
    "Width": number;
    "Height": number;
    "Fullscreen": boolean;

    /**
     * "auto", "discrete", "integrated"
     */
    "GPU": string;

    /**
     * validated argv prefix
     */
    "Wrapper": string[];
    "JavaPath": string;
    "JVMArgs": string[];

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("PlayerName" in $$source)) {
            this["PlayerName"] = "";
        }
        if (!("UUID" in $$source)) {
            this["UUID"] = "";
        }
        if (!("AccessToken" in $$source)) {
            this["AccessToken"] = "";
        }
        if (!("UserType" in $$source)) {
            this["UserType"] = "";
        }
        if (!("VersionID" in $$source)) {
            this["VersionID"] = "";
        }
        if (!("GameDir" in $$source)) {
            this["GameDir"] = "";
        }
        if (!("AssetsDir" in $$source)) {
            this["AssetsDir"] = "";
        }
        if (!("NativesDir" in $$source)) {
            this["NativesDir"] = "";
        }
        if (!("RamMB" in $$source)) {
            this["RamMB"] = 0;
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("Fullscreen" in $$source)) {
            this["Fullscreen"] = false;
        }
        if (!("GPU" in $$source)) {
            this["GPU"] = "";
        }
        if (!("Wrapper" in $$source)) {
            this["Wrapper"] = [];
        }
        if (!("JavaPath" in $$source)) {
            this["JavaPath"] = "";
        }
        if (!("JVMArgs" in $$source)) {
            this["JVMArgs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        const $$createField13_0 = $$createType0;
        const $$createField15_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Wrapper" in $$parsedSource) {
            $$parsedSource["Wrapper"] = $$createField13_0($$parsedSource["Wrapper"]);
        }
        if ("JVMArgs" in $$parsedSource) {
            $$parsedSource["JVMArgs"] = $$createField15_0($$parsedSource["JVMArgs"]);
        }
        return new Options($$parsedSource as Partial<Options>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
