// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Options holds launch configuration for a Minecraft instance.
 */
export interface Options {
    "PlayerName": string;
    "UUID": string;
    "AccessToken": string;

    /**
     * "offline", "ely.by", "microsoft"
     */
    "UserType": string;
    "VersionID": string;
    "GameDir": string;
    "AssetsDir": string;
    "NativesDir": string;
    "RamMB": number;
    "Width": number;
    "Height": number;
    "Fullscreen": boolean;

    /**
     * "auto", "discrete", "integrated"
     */
    "GPU": string;

    /**
     * validated argv prefix
     */
    "Wrapper": string[] | null;
    "JavaPath": string;
    "JVMArgs": string[] | null;
}
