// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService manages user accounts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateOffline creates an offline account with deterministic UUID.
 */
export function CreateOffline(username: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(1701179032, username);
}

/**
 * DeleteAccount removes an offline profile or revokes and removes an Ely.by/Microsoft session.
 */
export function DeleteAccount(accountUUID: string): $CancellablePromise<void> {
    return $Call.ByID(3349041341, accountUUID);
}

/**
 * ListAccounts returns all accounts.
 */
export function ListAccounts(): $CancellablePromise<$models.Account[] | null> {
    return $Call.ByID(2525240705);
}

export function LoginElyBy(username: string, password: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(2579944023, username, password);
}

/**
 * LoginMicrosoft runs the full Microsoft login flow in an in-app window.
 */
export function LoginMicrosoft(): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(4231905050);
}

export function LogoutElyBy(accountUUID: string): $CancellablePromise<void> {
    return $Call.ByID(3666026168, accountUUID);
}

/**
 * LogoutMicrosoft removes the keyring session and the account row.
 */
export function LogoutMicrosoft(accountUUID: string): $CancellablePromise<void> {
    return $Call.ByID(1581042649, accountUUID);
}

export function RefreshElyBy(accountUUID: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(24394337, accountUUID);
}

/**
 * RefreshMicrosoftToken explicitly refreshes a Microsoft session on demand.
 */
export function RefreshMicrosoftToken(accountUUID: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(935913693, accountUUID);
}

export function SelectAccount(accountUUID: string): $CancellablePromise<void> {
    return $Call.ByID(3495478380, accountUUID);
}
