// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService manages user accounts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "../auth/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelElyByOAuth ends a local device-code wait. The session itself
 * lives on the Ely.by website, so there is nothing to revoke locally;
 * the method exists so the frontend cancel path is explicit and typed.
 */
export function CancelElyByOAuth($0: string): $CancellablePromise<void> {
    return $Call.ByID(3411587455, $0);
}

/**
 * CreateOffline creates an offline account with deterministic UUID.
 */
export function CreateOffline(username: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(1701179032, username);
}

/**
 * DeleteAccount removes an offline profile or revokes and removes an Ely.by/Microsoft session.
 * The last remaining account cannot be removed; add another account first.
 */
export function DeleteAccount(accountUUID: string): $CancellablePromise<void> {
    return $Call.ByID(3349041341, accountUUID);
}

/**
 * FinishElyByOAuth polls once for the approved device code and creates
 * the Ely.by session. The frontend polls this method at the interval
 * from StartElyByOAuth until success, denial, expiry, or cancel.
 * 
 * Tokens live only in the OS keyring; accounts.json stays metadata-only.
 * On any failure after the token is stored, the token is removed so no
 * orphan secret survives.
 */
export function FinishElyByOAuth(deviceCode: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(1513048534, deviceCode);
}

/**
 * GetAccountSkin resolves the player's skin as a PNG data URL for the UI.
 * Offline profiles resolve the official default Steve template; Ely.by and
 * Microsoft profiles resolve their public session profile, then download the
 * allowlisted texture host. Failures return a generic error so the UI can
 * fall back to the initial-letter avatar.
 */
export function GetAccountSkin(accountUUID: string): $CancellablePromise<string> {
    return $Call.ByID(2101393135, accountUUID);
}

/**
 * ListAccounts returns all accounts.
 */
export function ListAccounts(): $CancellablePromise<$models.Account[] | null> {
    return $Call.ByID(2525240705);
}

export function LoginElyBy(username: string, password: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(2579944023, username, password);
}

/**
 * LoginMicrosoft runs the full Microsoft login flow in an in-app window.
 */
export function LoginMicrosoft(): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(4231905050);
}

export function LogoutElyBy(accountUUID: string): $CancellablePromise<void> {
    return $Call.ByID(3666026168, accountUUID);
}

/**
 * LogoutMicrosoft removes the keyring session and the account row.
 */
export function LogoutMicrosoft(accountUUID: string): $CancellablePromise<void> {
    return $Call.ByID(1581042649, accountUUID);
}

export function RefreshElyBy(accountUUID: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(24394337, accountUUID);
}

/**
 * RefreshMicrosoftToken explicitly refreshes a Microsoft session on demand.
 */
export function RefreshMicrosoftToken(accountUUID: string): $CancellablePromise<$models.Account | null> {
    return $Call.ByID(935913693, accountUUID);
}

export function SelectAccount(accountUUID: string): $CancellablePromise<void> {
    return $Call.ByID(3495478380, accountUUID);
}

/**
 * StartElyByOAuth opens an Ely.by device-code session. The frontend shows
 * the returned user code + verification URI; the player confirms on the
 * Ely.by website. No password ever enters the launcher.
 */
export function StartElyByOAuth(): $CancellablePromise<auth$0.ElyDeviceCodeStart> {
    return $Call.ByID(474463787);
}
