// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService manages artifact downloads.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as downloader$0 from "../downloader/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metadata$0 from "../metadata/models.js";

/**
 * DownloadPlan starts downloading all artifacts in the plan.
 */
export function DownloadPlan(plan: metadata$0.ArtifactPlan | null): $CancellablePromise<void> {
    return $Call.ByID(459453171, plan);
}

/**
 * RepairPlan re-downloads missing or corrupt artifacts.
 */
export function RepairPlan(plan: metadata$0.ArtifactPlan | null): $CancellablePromise<void> {
    return $Call.ByID(2797020082, plan);
}

/**
 * VerifyPlan checks all artifacts in the plan.
 */
export function VerifyPlan(plan: metadata$0.ArtifactPlan | null): $CancellablePromise<downloader$0.VerifyStatus[]> {
    return $Call.ByID(1439173882, plan).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = downloader$0.VerifyStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
