// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HomeService exposes instance actions in terms of persisted instance IDs.
 * The frontend never constructs artifact plans or launch command arguments.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as downloader$0 from "../downloader/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instances$0 from "../instances/models.js";

/**
 * CancelInstance cancels the active download or launch operation.
 */
export function CancelInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(909256986, id);
}

export function CreateInstance(name: string, version: string, loader: string, loaderVersion: string): $CancellablePromise<instances$0.Instance | null> {
    return $Call.ByID(2514643128, name, version, loader, loaderVersion);
}

export function DeleteInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(1735232051, id);
}

export function InstallInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(739998725, id);
}

export function LaunchInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(1169192303, id);
}

export function ListInstances(): $CancellablePromise<instances$0.Instance[] | null> {
    return $Call.ByID(3323204425);
}

/**
 * LoaderVersions returns versions of the selected Fabric or Quilt loader.
 */
export function LoaderVersions(loader: string, gameVersion: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(314266773, loader, gameVersion);
}

/**
 * RepairInstance restores missing or corrupt artifacts for an instance.
 */
export function RepairInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(27060533, id);
}

export function StopInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(4014632784, id);
}

/**
 * SupportedVersions returns stable releases listed by the selected metadata source.
 */
export function SupportedVersions(loader: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3952459278, loader);
}

/**
 * VerifyInstance checks the persisted artifact plan for an instance.
 */
export function VerifyInstance(id: string): $CancellablePromise<downloader$0.VerifyStatus[] | null> {
    return $Call.ByID(2734969665, id);
}
