// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HomeService exposes instance actions in terms of persisted instance IDs.
 * The frontend never constructs artifact plans or launch command arguments.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instances$0 from "../instances/models.js";

export function CreateInstance(name: string, version: string, loader: string): $CancellablePromise<instances$0.Instance | null> {
    return $Call.ByID(2514643128, name, version, loader);
}

export function DeleteInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(1735232051, id);
}

export function InstallInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(739998725, id);
}

export function LaunchInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(1169192303, id);
}

export function ListInstances(): $CancellablePromise<instances$0.Instance[] | null> {
    return $Call.ByID(3323204425);
}

export function StopInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(4014632784, id);
}
