// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstanceService manages Minecraft instances.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instances$0 from "../instances/models.js";

/**
 * CreateInstance creates a new instance.
 */
export function CreateInstance(name: string, mcVersion: string, loader: string): $CancellablePromise<instances$0.Instance | null> {
    return $Call.ByID(756819344, name, mcVersion, loader);
}

/**
 * DeleteInstance removes an instance.
 */
export function DeleteInstance(id: string): $CancellablePromise<void> {
    return $Call.ByID(816407771, id);
}

/**
 * GetInstance returns an instance by ID.
 */
export function GetInstance(id: string): $CancellablePromise<instances$0.Instance | null> {
    return $Call.ByID(1435565002, id);
}

/**
 * ListInstances returns all instances.
 */
export function ListInstances(): $CancellablePromise<instances$0.Instance[] | null> {
    return $Call.ByID(1171690641);
}

/**
 * OpenInstanceFolder opens a selected instance through the platform file manager.
 */
export function OpenInstanceFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(3321861240, id);
}

/**
 * TransitionState performs a state transition on an instance.
 */
export function TransitionState(id: string, newState: string): $CancellablePromise<void> {
    return $Call.ByID(3706498609, id, newState);
}

/**
 * UpdateInstanceSettings updates instance settings.
 */
export function UpdateInstanceSettings(id: string, settings: instances$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(672735392, id, settings);
}
