// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LaunchService manages Minecraft launch.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launch$0 from "../launch/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metadata$0 from "../metadata/models.js";

/**
 * Launch starts a Minecraft instance.
 */
export function Launch(detail: metadata$0.VersionDetail, opts: launch$0.Options): $CancellablePromise<void> {
    return $Call.ByID(3665090440, detail, opts);
}

/**
 * Stop stops a running instance.
 */
export function Stop(instanceID: string): $CancellablePromise<void> {
    return $Call.ByID(2189465455, instanceID);
}
