// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Account represents a user account.
 */
export class Account {
    "uuid": string;
    "username": string;
    "type": string;
    "displayName"?: string;
    "selected"?: boolean;

    /** Creates a new Account instance. */
    constructor($$source: Partial<Account> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     */
    static createFrom($$source: any = {}): Account {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account($$parsedSource as Partial<Account>);
    }
}

/**
 * DownloadProgressEvent is emitted during download operations.
 */
export class DownloadProgressEvent {
    "operationId": string;
    "instanceId": string;
    "status": string;
    "fileProgress": number;
    "totalFiles": number;
    "byteProgress": number;
    "totalBytes": number;
    "speed": number;
    "eta": number;
    "error"?: string;

    /** Creates a new DownloadProgressEvent instance. */
    constructor($$source: Partial<DownloadProgressEvent> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("instanceId" in $$source)) {
            this["instanceId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("fileProgress" in $$source)) {
            this["fileProgress"] = 0;
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }
        if (!("byteProgress" in $$source)) {
            this["byteProgress"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("eta" in $$source)) {
            this["eta"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadProgressEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadProgressEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadProgressEvent($$parsedSource as Partial<DownloadProgressEvent>);
    }
}

/**
 * InstanceStateEvent is emitted when instance state changes.
 */
export class InstanceStateEvent {
    "operationId"?: string;
    "instanceId": string;
    "oldState": string;
    "newState": string;

    /** Creates a new InstanceStateEvent instance. */
    constructor($$source: Partial<InstanceStateEvent> = {}) {
        if (!("instanceId" in $$source)) {
            this["instanceId"] = "";
        }
        if (!("oldState" in $$source)) {
            this["oldState"] = "";
        }
        if (!("newState" in $$source)) {
            this["newState"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstanceStateEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): InstanceStateEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstanceStateEvent($$parsedSource as Partial<InstanceStateEvent>);
    }
}

/**
 * JavaDownloadProgressEvent is emitted during JDK download operations.
 */
export class JavaDownloadProgressEvent {
    "major": number;
    "status": string;
    "bytesRead": number;
    "totalBytes": number;
    "speed": number;
    "eta": number;
    "error"?: string;

    /** Creates a new JavaDownloadProgressEvent instance. */
    constructor($$source: Partial<JavaDownloadProgressEvent> = {}) {
        if (!("major" in $$source)) {
            this["major"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("bytesRead" in $$source)) {
            this["bytesRead"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("eta" in $$source)) {
            this["eta"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JavaDownloadProgressEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): JavaDownloadProgressEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JavaDownloadProgressEvent($$parsedSource as Partial<JavaDownloadProgressEvent>);
    }
}

/**
 * LaunchStateEvent is emitted during launch lifecycle.
 */
export class LaunchStateEvent {
    "operationId"?: string;
    "instanceId": string;
    "state": string;
    "exitCode"?: number | null;
    "error"?: string;

    /** Creates a new LaunchStateEvent instance. */
    constructor($$source: Partial<LaunchStateEvent> = {}) {
        if (!("instanceId" in $$source)) {
            this["instanceId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchStateEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchStateEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LaunchStateEvent($$parsedSource as Partial<LaunchStateEvent>);
    }
}

/**
 * LogLineEvent is emitted for console/log output.
 */
export class LogLineEvent {
    "level": string;
    "message": string;
    "operationId"?: string;
    "instanceId"?: string;

    /** Creates a new LogLineEvent instance. */
    constructor($$source: Partial<LogLineEvent> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLineEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): LogLineEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLineEvent($$parsedSource as Partial<LogLineEvent>);
    }
}
