// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Account represents a user account.
 */
export class Account {
    "uuid": string;
    "username": string;
    "type": string;
    "displayName"?: string;

    /** Creates a new Account instance. */
    constructor($$source: Partial<Account> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     */
    static createFrom($$source: any = {}): Account {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account($$parsedSource as Partial<Account>);
    }
}
