// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account represents a user account.
 */
export interface Account {
    "uuid": string;
    "username": string;
    "type": string;
    "displayName"?: string;
    "selected"?: boolean;
}

/**
 * DownloadProgressEvent is emitted during download operations.
 */
export interface DownloadProgressEvent {
    "operationId": string;
    "instanceId": string;
    "status": string;
    "fileProgress": number;
    "totalFiles": number;
    "byteProgress": number;
    "totalBytes": number;
    "speed": number;
    "eta": number;
    "error"?: string;
}

/**
 * LaunchStateEvent is emitted during launch lifecycle.
 */
export interface LaunchStateEvent {
    "instanceId": string;
    "state": string;
    "exitCode"?: number | null;
}

/**
 * LogLineEvent is emitted for console/log output.
 */
export interface LogLineEvent {
    "level": string;
    "message": string;
    "operationId"?: string;
    "instanceId"?: string;
}
