// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService manages launcher settings and system operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instances$0 from "../instances/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as java$0 from "../java/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtimes$0 from "../runtimes/models.js";

/**
 * AddCustomJava verifies a Java executable before persisting it as a custom runtime.
 */
export function AddCustomJava(path: string): $CancellablePromise<java$0.JavaInfo | null> {
    return $Call.ByID(3970252539, path);
}

/**
 * CancelJavaDownload cancels an active JDK download.
 */
export function CancelJavaDownload(major: number): $CancellablePromise<void> {
    return $Call.ByID(1430642123, major);
}

/**
 * DeleteManagedRuntime removes a managed JDK runtime.
 */
export function DeleteManagedRuntime(major: number): $CancellablePromise<void> {
    return $Call.ByID(1950518885, major);
}

/**
 * DownloadJava starts downloading a managed JDK for the given major version.
 */
export function DownloadJava(major: number): $CancellablePromise<void> {
    return $Call.ByID(120327949, major);
}

/**
 * GetAppRoot returns the canonical data root for older clients.
 */
export function GetAppRoot(): $CancellablePromise<string> {
    return $Call.ByID(1669461666);
}

/**
 * GetDataRoot returns the canonical launcher data root.
 */
export function GetDataRoot(): $CancellablePromise<string> {
    return $Call.ByID(4258469607);
}

/**
 * GetSettings returns the current launcher settings.
 */
export function GetSettings(): $CancellablePromise<instances$0.LauncherDefaults> {
    return $Call.ByID(3632610702);
}

/**
 * IsJavaAvailable reports whether a Java runtime is available for the given major version.
 */
export function IsJavaAvailable(major: number): $CancellablePromise<boolean> {
    return $Call.ByID(2173746164, major);
}

/**
 * IsPortableMode reports whether launcher data is stored beside the executable.
 */
export function IsPortableMode(): $CancellablePromise<boolean> {
    return $Call.ByID(1688164893);
}

/**
 * JavaRuntimes returns all verified runtimes, marking the PATH runtime and custom entries.
 */
export function JavaRuntimes(): $CancellablePromise<java$0.JavaInfo[] | null> {
    return $Call.ByID(1197596420);
}

/**
 * ListManagedRuntimes returns all installed managed JDK runtimes.
 */
export function ListManagedRuntimes(): $CancellablePromise<runtimes$0.ManagedRuntime[] | null> {
    return $Call.ByID(2972888975);
}

export function OpenAppRoot(): $CancellablePromise<void> {
    return $Call.ByID(485223332);
}

/**
 * OpenBrowserURL opens the Ely.by verification page in the user's default
 * browser. The platform package validates the host before launching it.
 */
export function OpenBrowserURL(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(1352130944, rawURL);
}

export function OpenGameRoot(): $CancellablePromise<void> {
    return $Call.ByID(2958749619);
}

/**
 * OpenLogFolder opens the canonical data root's log directory.
 */
export function OpenLogFolder(): $CancellablePromise<void> {
    return $Call.ByID(739377113);
}

/**
 * RequiredJavaMajor returns the minimum Java major version for a Minecraft
 * version, e.g. 21 for "1.20.1". Used by the UI for compatibility guidance.
 */
export function RequiredJavaMajor(mcVersion: string): $CancellablePromise<number> {
    return $Call.ByID(73167809, mcVersion);
}

/**
 * ScanJava detects installed Java installations.
 */
export function ScanJava(): $CancellablePromise<java$0.JavaInfo[] | null> {
    return $Call.ByID(4149514100);
}

/**
 * UpdateDataRoot stores the canonical data root to use after the launcher restarts.
 */
export function UpdateDataRoot(path: string): $CancellablePromise<void> {
    return $Call.ByID(3859935312, path);
}

/**
 * UpdateSettings updates the launcher settings.
 */
export function UpdateSettings(settings: instances$0.LauncherDefaults): $CancellablePromise<void> {
    return $Call.ByID(3129792477, settings);
}

/**
 * ValidateJavaPath checks if a Java path is valid and compatible.
 */
export function ValidateJavaPath(path: string, requiredMajor: number): $CancellablePromise<java$0.JavaInfo | null> {
    return $Call.ByID(4219157576, path, requiredMajor);
}
