// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JavaInfo holds information about a detected Java installation.
 */
export interface JavaInfo {
    "path": string;
    "version": string;
    "major": number;
}
