// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * JavaInfo holds information about a detected Java installation.
 */
export class JavaInfo {
    "path": string;
    "version": string;
    "major": number;

    /** Creates a new JavaInfo instance. */
    constructor($$source: Partial<JavaInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("major" in $$source)) {
            this["major"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JavaInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): JavaInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JavaInfo($$parsedSource as Partial<JavaInfo>);
    }
}
