// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Instance represents a Minecraft instance.
 */
export class Instance {
    "id": string;
    "name": string;
    "mcVersion": string;
    "loader": LoaderType;
    "state": InstanceState;
    "settings": Settings;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Instance instance. */
    constructor($$source: Partial<Instance> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mcVersion" in $$source)) {
            this["mcVersion"] = "";
        }
        if (!("loader" in $$source)) {
            this["loader"] = LoaderType.$zero;
        }
        if (!("state" in $$source)) {
            this["state"] = InstanceState.$zero;
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new Settings());
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Instance instance from a string or object.
     */
    static createFrom($$source: any = {}): Instance {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField5_0($$parsedSource["settings"]);
        }
        return new Instance($$parsedSource as Partial<Instance>);
    }
}

/**
 * InstanceState represents the current state of an instance.
 */
export enum InstanceState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateNotInstalled = "not_installed",
    StatePlanning = "planning",
    StateDownloading = "downloading",
    StateVerifying = "verifying",
    StateReady = "ready",
    StateRunning = "running",
    StateStopped = "stopped",
    StateCrashed = "crashed",
    StateFailed = "failed",
};

/**
 * LauncherDefaults holds global launcher settings that instances inherit from.
 */
export class LauncherDefaults {
    "theme": string;
    "closeAction": string;
    "windowMode": string;
    "defaultMinRamMB": number;
    "defaultMaxRamMB": number;
    "defaultResolutionW": number;
    "defaultResolutionH": number;
    "defaultJavaPath": string;
    "defaultJvmArgs": string;
    "gpuPreference": string;
    "wrapperCommand": string;

    /** Creates a new LauncherDefaults instance. */
    constructor($$source: Partial<LauncherDefaults> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("closeAction" in $$source)) {
            this["closeAction"] = "";
        }
        if (!("windowMode" in $$source)) {
            this["windowMode"] = "";
        }
        if (!("defaultMinRamMB" in $$source)) {
            this["defaultMinRamMB"] = 0;
        }
        if (!("defaultMaxRamMB" in $$source)) {
            this["defaultMaxRamMB"] = 0;
        }
        if (!("defaultResolutionW" in $$source)) {
            this["defaultResolutionW"] = 0;
        }
        if (!("defaultResolutionH" in $$source)) {
            this["defaultResolutionH"] = 0;
        }
        if (!("defaultJavaPath" in $$source)) {
            this["defaultJavaPath"] = "";
        }
        if (!("defaultJvmArgs" in $$source)) {
            this["defaultJvmArgs"] = "";
        }
        if (!("gpuPreference" in $$source)) {
            this["gpuPreference"] = "";
        }
        if (!("wrapperCommand" in $$source)) {
            this["wrapperCommand"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LauncherDefaults instance from a string or object.
     */
    static createFrom($$source: any = {}): LauncherDefaults {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LauncherDefaults($$parsedSource as Partial<LauncherDefaults>);
    }
}

/**
 * LoaderType identifies the mod loader.
 */
export enum LoaderType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LoaderVanilla = "vanilla",
    LoaderFabric = "fabric",
    LoaderQuilt = "quilt",
};

/**
 * Settings holds per-instance launch settings.
 */
export class Settings {
    "minRamMB"?: number | null;
    "maxRamMB"?: number | null;
    "resolutionW"?: number | null;
    "resolutionH"?: number | null;
    "javaPath"?: string | null;
    "jvmArgs"?: string | null;
    "windowMode"?: string | null;
    "gpuPreference"?: string | null;
    "wrapperCommand"?: string | null;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = Settings.createFrom;
