// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Instance represents a Minecraft instance.
 */
export interface Instance {
    "id": string;
    "name": string;
    "mcVersion": string;
    "loader": LoaderType;
    "loaderVersion"?: string;
    "state": InstanceState;
    "settings": Settings;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * InstanceState represents the current state of an instance.
 */
export enum InstanceState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateNotInstalled = "not_installed",
    StatePlanning = "planning",
    StateDownloading = "downloading",
    StateVerifying = "verifying",
    StateReady = "ready",
    StateRunning = "running",
    StateStopped = "stopped",
    StateCrashed = "crashed",
    StateFailed = "failed",
};

/**
 * LauncherDefaults holds global launcher settings that instances inherit from.
 */
export interface LauncherDefaults {
    "theme": string;
    "closeAction": string;
    "windowMode": string;
    "defaultMinRamMB": number;
    "defaultMaxRamMB": number;
    "defaultResolutionW": number;
    "defaultResolutionH": number;
    "defaultJavaPath": string;
    "customJavaPaths"?: string[] | null;
    "javaDefaultInitialized": boolean;
    "defaultJvmArgs": string;
    "gpuPreference": string;
    "wrapperCommand": string;
}

/**
 * LoaderType identifies the mod loader.
 */
export enum LoaderType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LoaderVanilla = "vanilla",
    LoaderFabric = "fabric",
    LoaderQuilt = "quilt",
};

/**
 * Settings holds per-instance launch settings.
 */
export interface Settings {
    "minRamMB"?: number | null;
    "maxRamMB"?: number | null;
    "resolutionW"?: number | null;
    "resolutionH"?: number | null;
    "javaPath"?: string | null;
    "jvmArgs"?: string | null;
    "windowMode"?: string | null;
    "gpuPreference"?: string | null;
    "wrapperCommand"?: string | null;
}
