// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metadata$0 from "../metadata/models.js";

/**
 * VerifyStatus is the result of verifying a single artifact.
 */
export interface VerifyStatus {
    "Artifact": metadata$0.Artifact;
    "Valid": boolean;
    "Missing": boolean;
    "Corrupt": boolean;
    "Error": any;
}
