// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ElyDeviceCodeStart is the user-facing part of a device-code session.
 * DeviceCode stays backend-side where possible; the frontend needs it
 * only to drive Finish/Poll and Cancel calls.
 */
export class ElyDeviceCodeStart {
    "deviceCode": string;
    "userCode": string;
    "verificationUri": string;
    "expiresIn": number;
    "interval": number;

    /** Creates a new ElyDeviceCodeStart instance. */
    constructor($$source: Partial<ElyDeviceCodeStart> = {}) {
        if (!("deviceCode" in $$source)) {
            this["deviceCode"] = "";
        }
        if (!("userCode" in $$source)) {
            this["userCode"] = "";
        }
        if (!("verificationUri" in $$source)) {
            this["verificationUri"] = "";
        }
        if (!("expiresIn" in $$source)) {
            this["expiresIn"] = 0;
        }
        if (!("interval" in $$source)) {
            this["interval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ElyDeviceCodeStart instance from a string or object.
     */
    static createFrom($$source: any = {}): ElyDeviceCodeStart {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ElyDeviceCodeStart($$parsedSource as Partial<ElyDeviceCodeStart>);
    }
}
