// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ElyDeviceCodeStart is the user-facing part of a device-code session.
 * DeviceCode stays backend-side where possible; the frontend needs it
 * only to drive Finish/Poll and Cancel calls.
 */
export interface ElyDeviceCodeStart {
    "deviceCode": string;
    "userCode": string;
    "verificationUri": string;
    "expiresIn": number;
    "interval": number;
}
