// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ManagedRuntime represents a downloaded and extracted JDK runtime.
 */
export class ManagedRuntime {
    "major": number;
    "version": string;
    "path": string;
    "installed": boolean;
    "size"?: number;

    /** Creates a new ManagedRuntime instance. */
    constructor($$source: Partial<ManagedRuntime> = {}) {
        if (!("major" in $$source)) {
            this["major"] = 0;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedRuntime instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagedRuntime {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManagedRuntime($$parsedSource as Partial<ManagedRuntime>);
    }
}
