// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JavaDownloadProgressEvent is emitted via Wails events during JDK downloads.
 */
export interface JavaDownloadProgressEvent {
    "major": number;
    "status": string;
    "bytesRead": number;
    "totalBytes": number;
    "speed": number;
    "eta": number;
    "error"?: string;
}

/**
 * ManagedRuntime represents a downloaded and extracted JDK runtime.
 */
export interface ManagedRuntime {
    "major": number;
    "version": string;
    "path": string;
    "installed": boolean;
    "size"?: number;
}
